// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: address_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createAddress = `-- name: CreateAddress :exec
INSERT INTO addresses (
    addressId,
    country,
    region,
    province,
    city,
    barangay,
    addressDetails,
    userId
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING addressid, country, region, province, city, barangay, addressdetails, userid
`

type CreateAddressParams struct {
	Addressid      string
	Country        string
	Region         sql.NullString
	Province       sql.NullString
	City           sql.NullString
	Barangay       sql.NullString
	Addressdetails sql.NullString
	Userid         sql.NullString
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) error {
	_, err := q.db.ExecContext(ctx, createAddress,
		arg.Addressid,
		arg.Country,
		arg.Region,
		arg.Province,
		arg.City,
		arg.Barangay,
		arg.Addressdetails,
		arg.Userid,
	)
	return err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses
WHERE addressId = ? AND userId = ?
`

type DeleteAddressParams struct {
	Addressid string
	Userid    sql.NullString
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.ExecContext(ctx, deleteAddress, arg.Addressid, arg.Userid)
	return err
}

const getAllAddressByUserId = `-- name: GetAllAddressByUserId :many
SELECT addressid, country, region, province, city, barangay, addressdetails, userid FROM addresses
WHERE userId = ?
`

func (q *Queries) GetAllAddressByUserId(ctx context.Context, userid sql.NullString) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getAllAddressByUserId, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.Addressid,
			&i.Country,
			&i.Region,
			&i.Province,
			&i.City,
			&i.Barangay,
			&i.Addressdetails,
			&i.Userid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
