// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: application_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    applicationId, 
    proposalLink, 
    status, 
    postId, 
    userId, 
    created_at, 
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING applicationid, proposallink, status, postid, userid, created_at, updated_at
`

type CreateApplicationParams struct {
	Applicationid string
	Proposallink  sql.NullString
	Status        string
	Postid        string
	Userid        string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.Applicationid,
		arg.Proposallink,
		arg.Status,
		arg.Postid,
		arg.Userid,
	)
	var i Application
	err := row.Scan(
		&i.Applicationid,
		&i.Proposallink,
		&i.Status,
		&i.Postid,
		&i.Userid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
