// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Address struct {
	Addressid      string
	Country        string
	Region         sql.NullString
	Province       sql.NullString
	City           sql.NullString
	Barangay       sql.NullString
	Addressdetails sql.NullString
	Orgid          string
}

type Application struct {
	Applicationid string
	Resumelink    sql.NullString
	Status        string
	Postid        string
	Userid        string
	CreatedAt     interface{}
	UpdatedAt     interface{}
}

type JobDetail struct {
	Jobdetailid     string
	Postid          string
	Jobtype         string
	Salarytype      sql.NullString
	Salaryamountmin sql.NullInt64
	Salaryamountmax sql.NullInt64
	Salarycurrency  sql.NullString
}

type Organization struct {
	Orgid        string
	Company      string
	Email        string
	Mobilenumber sql.NullString
	Bannerlink   sql.NullString
	Logolink     sql.NullString
	Userid       string
	CreatedAt    sql.NullTime
	UpdatedAt    interface{}
}

type Post struct {
	Postid             string
	Title              string
	Description        sql.NullString
	Additionalinfolink sql.NullString
	Wfh                sql.NullInt64
	Deadline           sql.NullInt64
	Embedding          interface{}
	PostedAt           sql.NullTime
	UpdatedAt          sql.NullTime
	Addressid          string
	Orgid              string
}

type PostRequirement struct {
	Requirementid   string
	Postid          string
	Requirementtype string
	Requirement     string
}

type PostTag struct {
	Tagid       string
	Postid      string
	Tagname     string
	Tagcategory sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	Userid       string
	Firstname    string
	Lastname     string
	Email        string
	Mobilenumber sql.NullString
	Resumelink   sql.NullString
	GoogleID     sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type UserSkill struct {
	Skillid       string
	Userid        string
	Skillname     string
	Skilllevel    sql.NullString
	Skillcategory sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}
