// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type User struct {
	Userid    interface{}
	Firstname string
	Lastname  string
	Email     string
	Password  string
	CreatedAt interface{}
	UpdatedAt interface{}
}
