// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: org_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (
    orgId, 
    company, 
    email, 
    mobileNumber, 
    posterLink, 
    logoLink
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type CreateOrganizationParams struct {
	Orgid        string
	Company      string
	Email        string
	Mobilenumber sql.NullString
	Posterlink   sql.NullString
	Logolink     sql.NullString
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.Orgid,
		arg.Company,
		arg.Email,
		arg.Mobilenumber,
		arg.Posterlink,
		arg.Logolink,
	)
	return err
}
